.Dd 2/20/14
.Dt windowstack 1
.Os Darwin
.Sh NAME
.Nm windowstack
.Nd Track OS X window titles
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
Continuously prints the application name and title of the focused window.
.Sh FILES
.Bl -tag -width "/usr/local/share/man/man1/windowstack.1" -compact
.It Pa /usr/local/bin/windowstack
The
.Nm
binary
.It Pa /usr/local/share/man/man1/windowstack.1
This man page
.El
.Sh SEE ALSO
.Ar https://github.com/cdzombak/WindowStack/
.Sh BUGS
.Ar https://github.com/cdzombak/WindowStack/issues
.Sh CONTRIBUTORS
.Bl -tag -width "Chris Dzombak" -compact
.It Chris Dzombak
.Ar https://github.com/cdzombak
.El
.Sh LICENSE
.Nm
is distributed under the MIT license; (c) 2014.